# generic wifi
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_ti
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_ti
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true

BOARD_SEPOLICY_DIRS += \
	device/ti/am62x/shared/wifi/sepolicy
